graph TD;
    subgraph Notification Server
        T1[[Topic 1]]
        T2[[Topic 2]]
        T3[[Topic 3]]
    end

    subgraph Plateforme
        P1(Publisher 1)
        P2(Publisher 2)
    end

    subgraph User Browser
        S1([Subscriber 1])
        S2([Subscriber 2])
        S3([Subscriber 3])
        S4([Subscriber 4])

    end

    P1 --Publishes msg----> T1
    P2 --Publishes msg----> T2
    P2 --Publishes msg----> T3
    
    T2 <--Subscribes/Receives msg---> S1
    T1 <--Subscribes/Receives msg---> S2
    T3 <--Subscribes/Receives msg---> S3
    T2 <--Subscribes/Receives msg---> S4

    
    
    

    
    
    
    
